---
- name: Print Hello, World! and Save Execution Time
  hosts: all
  remote_user: testing
  become: yes
  become_method: su
  vars:
    ansible_become_password: s

  tasks:
    - name: Record execution start time
      command: "/bin/date +%s.%N"
      register: start_time

    - name: Sleep for a few seconds (Replace with your actual tasks)
      command: "sleep 5s"
      async: 300
      poll: 0
      ignore_errors: yes

    - name: Create file in /tmp/sonu
      become: yes
      file:
        path: "/tmp/sonu.txt"
        state: touch

    - name: Record execution end time
      command: "/bin/date +%s.%N"
      register: end_time

    - name: Calculate execution time
      shell: "echo {{ (end_time.stdout | float) - (start_time.stdout | float) }} > /tmp/execution_time.txt"
