---
- name: Print Hello, World! and Save Execution Time
  hosts: all
  gather_facts: false
  tasks:
          
     - name: Print Hello, World!
       debug:
        msg: "Hello, World!"

     - name: Create the time file
       file: touch /tmp/time_file.txt

     - name: Save Execution Time
       file: date +%Y-%m-%d_%H-%M-%S
       register: time_output
       
     - name: Save the execution time to a file
       copy:
        content: "{{ time_output.stdout }}"
        dest: /tmp/time_file.txt
